"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Save, Download } from "lucide-react"

interface TechnologyFormData {
  technologyAffectsEveryday: string
  worldCharacterEmbraceTechnology: string
  technologyDividesPeople: string
  technologyBringsPeopleTogether: string
  previousTechnologiesObsolete: string
  newTechnologiesDevelopSpeed: string
  technologyDevelopedIllogical: string
  technologicalDiscoveryShapedWorld: string
  drivingForceNewDevelopments: string
  magicOrScience: string
  earliestRecordedTechnology: string
  whoUsesNewTechnologies: string
  whoHoldsOldTechnologies: string
  whoInventsNewTechnologies: string
}

export function TechnologyForm() {
  const [isExpanded, setIsExpanded] = useState(false)
  const [formData, setFormData] = useState<TechnologyFormData>({
    technologyAffectsEveryday: "",
    worldCharacterEmbraceTechnology: "",
    technologyDividesPeople: "",
    technologyBringsPeopleTogether: "",
    previousTechnologiesObsolete: "",
    newTechnologiesDevelopSpeed: "",
    technologyDevelopedIllogical: "",
    technologicalDiscoveryShapedWorld: "",
    drivingForceNewDevelopments: "",
    magicOrScience: "",
    earliestRecordedTechnology: "",
    whoUsesNewTechnologies: "",
    whoHoldsOldTechnologies: "",
    whoInventsNewTechnologies: ""
  })

  const handleInputChange = (field: keyof TechnologyFormData, value: string) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }))
  }

  const handleSave = () => {
    console.log("Technology form saved:", formData)
    alert("Technology form saved successfully")
  }

  const handleExport = () => {
    const content = `TECHNOLOGY - FORM COMPLETED

HOW DOES TECHNOLOGY AFFECT THE EVERYDAY?
${formData.technologyAffectsEveryday}

DOES THE WORLD / CHARACTER EMBRACE NEW TECHNOLOGY? WHY OR WHY NOT?
${formData.worldCharacterEmbraceTechnology}

HOW DOES TECHNOLOGY DIVIDE PEOPLE?
${formData.technologyDividesPeople}

HOW DOES TECHNOLOGY BRING PEOPLE TOGETHER?
${formData.technologyBringsPeopleTogether}

WHAT PREVIOUS TECHNOLOGIES HAVE BECOME OBSOLETE?
${formData.previousTechnologiesObsolete}

HOW QUICKLY DO NEW TECHNOLOGIES DEVELOP?
${formData.newTechnologiesDevelopSpeed}

HOW HAS TECHNOLOGY DEVELOPED IN A WAY THAT IS ILLOGICAL OR INEFFICIENT IN HINDSIGHT?
${formData.technologyDevelopedIllogical}

WHAT TECHNOLOGICAL DISCOVERY HAS SHAPED THE WORLD?
${formData.technologicalDiscoveryShapedWorld}

WHAT IS THE DRIVING FORCE BEHIND NEW DEVELOPMENTS?
${formData.drivingForceNewDevelopments}

MAGIC OR SCIENCE?
${formData.magicOrScience}

WHAT IS THE EARLIEST RECORDED TECHNOLOGY?
${formData.earliestRecordedTechnology}

WHO USES NEW TECHNOLOGIES?
${formData.whoUsesNewTechnologies}

WHO HOLDS ONTO OLD TECHNOLOGIES?
${formData.whoHoldsOldTechnologies}

WHO INVENTS NEW TECHNOLOGIES?
${formData.whoInventsNewTechnologies}

© E.A. DEVERELL - http://eadeverell.com
Generated by Narratica AI Creative Tools`

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `technology-form.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-3">
      <Button
        onClick={() => setIsExpanded(!isExpanded)}
        className="w-full justify-start border-purple-600/30 hover:bg-purple-800/20 bg-transparent"
      >
        <div className="w-6 h-6 rounded bg-white/20 flex items-center justify-center mr-3">
          <span className="text-xs font-bold">⚡</span>
        </div>
        Technology
        <span className="ml-auto text-xs text-muted-foreground">
          {isExpanded ? '▼' : '▶'}
        </span>
      </Button>

      {isExpanded && (
        <div className="bg-slate-800/30 border border-purple-800/30 rounded-lg p-4 space-y-4 max-h-[70vh] overflow-y-auto">
          <div className="text-center mb-4">
            <h3 className="text-lg font-semibold text-white mb-2">Technology</h3>
            <p className="text-sm text-muted-foreground">Explore the role of technology in your world</p>
          </div>

          {/* Main Questions */}
          <div className="space-y-4">
            <div>
              <Label className="text-white font-semibold text-sm">HOW DOES TECHNOLOGY AFFECT THE EVERYDAY?</Label>
              <Textarea
                value={formData.technologyAffectsEveryday}
                onChange={(e) => handleInputChange('technologyAffectsEveryday', e.target.value)}
                placeholder="Describe how technology impacts daily life..."
                className="mt-1 bg-slate-700 border-purple-800/30 text-white min-h-[60px] text-sm"
              />
            </div>

            <div>
              <Label className="text-white font-semibold text-sm">DOES THE WORLD / CHARACTER EMBRACE NEW TECHNOLOGY? WHY OR WHY NOT?</Label>
              <Textarea
                value={formData.worldCharacterEmbraceTechnology}
                onChange={(e) => handleInputChange('worldCharacterEmbraceTechnology', e.target.value)}
                placeholder="Describe attitudes towards new technology and the reasons behind them..."
                className="mt-1 bg-slate-700 border-purple-800/30 text-white min-h-[60px] text-sm"
              />
            </div>

            <div>
              <Label className="text-white font-semibold text-sm">HOW DOES TECHNOLOGY DIVIDE PEOPLE?</Label>
              <Textarea
                value={formData.technologyDividesPeople}
                onChange={(e) => handleInputChange('technologyDividesPeople', e.target.value)}
                placeholder="Describe how technology creates divisions between people..."
                className="mt-1 bg-slate-700 border-purple-800/30 text-white min-h-[60px] text-sm"
              />
            </div>

            <div>
              <Label className="text-white font-semibold text-sm">HOW DOES TECHNOLOGY BRING PEOPLE TOGETHER?</Label>
              <Textarea
                value={formData.technologyBringsPeopleTogether}
                onChange={(e) => handleInputChange('technologyBringsPeopleTogether', e.target.value)}
                placeholder="Describe how technology connects and unites people..."
                className="mt-1 bg-slate-700 border-purple-800/30 text-white min-h-[60px] text-sm"
              />
            </div>

            <div>
              <Label className="text-white font-semibold text-sm">WHAT PREVIOUS TECHNOLOGIES HAVE BECOME OBSOLETE?</Label>
              <Textarea
                value={formData.previousTechnologiesObsolete}
                onChange={(e) => handleInputChange('previousTechnologiesObsolete', e.target.value)}
                placeholder="List technologies that are no longer used or relevant..."
                className="mt-1 bg-slate-700 border-purple-800/30 text-white min-h-[60px] text-sm"
              />
            </div>

            <div>
              <Label className="text-white font-semibold text-sm">HOW QUICKLY DO NEW TECHNOLOGIES DEVELOP?</Label>
              <Select value={formData.newTechnologiesDevelopSpeed} onValueChange={(value: string) => handleInputChange('newTechnologiesDevelopSpeed', value)}>
                <SelectTrigger className="mt-1 bg-slate-700 border-purple-800/30 text-white text-sm">
                  <SelectValue placeholder="Select development speed..." />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Very Slow">Very Slow (centuries)</SelectItem>
                  <SelectItem value="Slow">Slow (decades)</SelectItem>
                  <SelectItem value="Moderate">Moderate (years)</SelectItem>
                  <SelectItem value="Fast">Fast (months)</SelectItem>
                  <SelectItem value="Very Fast">Very Fast (weeks/days)</SelectItem>
                  <SelectItem value="Instantaneous">Instantaneous</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div>
              <Label className="text-white font-semibold text-sm">HOW HAS TECHNOLOGY DEVELOPED IN A WAY THAT IS ILLOGICAL OR INEFFICIENT IN HINDSIGHT?</Label>
              <Textarea
                value={formData.technologyDevelopedIllogical}
                onChange={(e) => handleInputChange('technologyDevelopedIllogical', e.target.value)}
                placeholder="Describe technological developments that seem illogical or inefficient..."
                className="mt-1 bg-slate-700 border-purple-800/30 text-white min-h-[60px] text-sm"
              />
            </div>

            <div>
              <Label className="text-white font-semibold text-sm">WHAT TECHNOLOGICAL DISCOVERY HAS SHAPED THE WORLD?</Label>
              <Textarea
                value={formData.technologicalDiscoveryShapedWorld}
                onChange={(e) => handleInputChange('technologicalDiscoveryShapedWorld', e.target.value)}
                placeholder="Describe the most influential technological discovery..."
                className="mt-1 bg-slate-700 border-purple-800/30 text-white min-h-[60px] text-sm"
              />
            </div>

            <div>
              <Label className="text-white font-semibold text-sm">WHAT IS THE DRIVING FORCE BEHIND NEW DEVELOPMENTS?</Label>
              <Textarea
                value={formData.drivingForceNewDevelopments}
                onChange={(e) => handleInputChange('drivingForceNewDevelopments', e.target.value)}
                placeholder="Describe what motivates technological advancement..."
                className="mt-1 bg-slate-700 border-purple-800/30 text-white min-h-[60px] text-sm"
              />
            </div>

            <div>
              <Label className="text-white font-semibold text-sm">MAGIC OR SCIENCE?</Label>
              <Select value={formData.magicOrScience} onValueChange={(value: string) => handleInputChange('magicOrScience', value)}>
                <SelectTrigger className="mt-1 bg-slate-700 border-purple-800/30 text-white text-sm">
                  <SelectValue placeholder="Select approach..." />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Pure Magic">Pure Magic</SelectItem>
                  <SelectItem value="Pure Science">Pure Science</SelectItem>
                  <SelectItem value="Magic as Science">Magic as Science</SelectItem>
                  <SelectItem value="Science as Magic">Science as Magic</SelectItem>
                  <SelectItem value="Both Separate">Both Separate</SelectItem>
                  <SelectItem value="Interconnected">Interconnected</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div>
              <Label className="text-white font-semibold text-sm">WHAT IS THE EARLIEST RECORDED TECHNOLOGY?</Label>
              <Textarea
                value={formData.earliestRecordedTechnology}
                onChange={(e) => handleInputChange('earliestRecordedTechnology', e.target.value)}
                placeholder="Describe the first known technology in your world..."
                className="mt-1 bg-slate-700 border-purple-800/30 text-white min-h-[60px] text-sm"
              />
            </div>

            <div>
              <Label className="text-white font-semibold text-sm">WHO USES NEW TECHNOLOGIES?</Label>
              <Textarea
                value={formData.whoUsesNewTechnologies}
                onChange={(e) => handleInputChange('whoUsesNewTechnologies', e.target.value)}
                placeholder="Describe who adopts new technologies first..."
                className="mt-1 bg-slate-700 border-purple-800/30 text-white min-h-[60px] text-sm"
              />
            </div>

            <div>
              <Label className="text-white font-semibold text-sm">WHO HOLDS ONTO OLD TECHNOLOGIES?</Label>
              <Textarea
                value={formData.whoHoldsOldTechnologies}
                onChange={(e) => handleInputChange('whoHoldsOldTechnologies', e.target.value)}
                placeholder="Describe who resists change and keeps old technologies..."
                className="mt-1 bg-slate-700 border-purple-800/30 text-white min-h-[60px] text-sm"
              />
            </div>

            <div>
              <Label className="text-white font-semibold text-sm">WHO INVENTS NEW TECHNOLOGIES?</Label>
              <Textarea
                value={formData.whoInventsNewTechnologies}
                onChange={(e) => handleInputChange('whoInventsNewTechnologies', e.target.value)}
                placeholder="Describe who creates and develops new technologies..."
                className="mt-1 bg-slate-700 border-purple-800/30 text-white min-h-[60px] text-sm"
              />
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-2 pt-4 border-t border-purple-800/30">
            <Button
              onClick={handleSave}
              className="flex-1 bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white text-sm"
            >
              <Save className="w-4 h-4 mr-2" />
              Save
            </Button>
            <Button
              onClick={handleExport}
              variant="outline"
              className="flex-1 border-purple-800/30 text-white hover:bg-purple-800/20 text-sm"
            >
              <Download className="w-4 h-4 mr-2" />
              Export
            </Button>
          </div>
        </div>
      )}
    </div>
  )
}
